import type { ThemeDefinition } from 'vuetify'

export const staticPrimaryColor = '#44797F'
export const staticPrimaryDarkenColor = '#44797F'

export const themes: Record<string, ThemeDefinition> = {
  light: {
    dark: false,
    colors: {
      'primary': staticPrimaryColor,
      'on-primary': '#fff',
      'primary-darken-1': '#44797F',
      'secondary': '#97D5DE',
      'secondary-darken-1': '#78BBC5',
      'on-secondary': '#fff',
      'success': '#56CA00',
      'success-darken-1': '#4DB600',
      'on-success': '#fff',
      'info': '#97D5DE',
      'info-darken-1': '#78BBC5',
      'on-info': '#fff',
      'warning': '#FFB400',
      'warning-darken-1': '#E6A200',
      'on-warning': '#fff',
      'error': '#FF401B',
      'error-darken-1': '#FF401B',
      'on-error': '#fff',
      'background': '#F2F4F1',
      'on-background': '#1B1D1A',
      'surface': '#fff',
      'on-surface': '#1B1D1A',
      'grey-50': '#FAFAFA',
      'grey-100': '#F5F5F5',
      'grey-200': '#EEEEEE',
      'grey-300': '#E0E0E0',
      'grey-400': '#BDBDBD',
      'grey-500': '#9E9E9E',
      'grey-600': '#757575',
      'grey-700': '#616161',
      'grey-800': '#424242',
      'grey-900': '#212121',
      'perfect-scrollbar-thumb': '#dbdade',
      'skin-bordered-background': '#fff',
      'skin-bordered-surface': '#fff',
      'expansion-panel-text-custom-bg': '#fafafa',
      'track-bg': '#F0F2F8',
      'chat-bg': '#F7F6FA',
    },

    variables: {
      'code-color': '#44797F',
      'overlay-scrim-background': '#2E263D',
      'tooltip-background': '#1A0E33',
      'overlay-scrim-opacity': 0.5,
      'hover-opacity': 0.04,
      'focus-opacity': 0.1,
      'selected-opacity': 0.08,
      'activated-opacity': 0.16,
      'pressed-opacity': 0.14,
      'dragged-opacity': 0.1,
      'disabled-opacity': 0.4,
      'border-color': '#2E263D',
      'border-opacity': 0.12,
      'table-header-color': '#F6F7FB',
      'high-emphasis-opacity': 0.9,
      'medium-emphasis-opacity': 0.7,

      // 👉 shadows
      'shadow-key-umbra-color': '#2E263D',
      'shadow-xs-opacity': '0.16',
      'shadow-sm-opacity': '0.18',
      'shadow-md-opacity': '0.20',
      'shadow-lg-opacity': '0.22',
      'shadow-xl-opacity': '0.24',
    },
  },

  dark: {
    dark: true,
    colors: {
      'primary': staticPrimaryColor,
      'on-primary': '#fff',
      'primary-darken-1': '#44797F',
      'secondary': '#97D5DE',
      'secondary-darken-1': '#78BBC5',
      'on-secondary': '#fff',
      'success': '#34D399',
      'success-darken-1': '#10B981',
      'on-success': '#fff',
      'info': '#97D5DE',
      'info-darken-1': '#78BBC5',
      'on-info': '#fff',
      'warning': '#FFB400',
      'warning-darken-1': '#E6A200',
      'on-warning': '#fff',
      'error': '#FF401B',
      'error-darken-1': '#FF401B',
      'on-error': '#fff',
      'background': '#1B1D1A',
      'on-background': '#EBEBEB',
      'surface': '#232622',
      'on-surface': '#EBEBEB',
      'grey-50': '#20231F',
      'grey-100': '#262925',
      'grey-200': '#30342F',
      'grey-300': '#454A43',
      'grey-400': '#686F65',
      'grey-500': '#899087',
      'grey-600': '#A9AFA7',
      'grey-700': '#C1C6BF',
      'grey-800': '#D8DCD6',
      'grey-900': '#EBEBEB',
      'perfect-scrollbar-thumb': '#44797F',
      'skin-bordered-background': '#1B1D1A',
      'skin-bordered-surface': '#232622',
      'expansion-panel-text-custom-bg': '#262925',
      'track-bg': '#30342F',
      'chat-bg': '#20231F',
    },

    variables: {
      'code-color': '#44797F',
      'overlay-scrim-background': '#11130F',
      'tooltip-background': '#EBEBEB',
      'overlay-scrim-opacity': 0.5,
      'hover-opacity': 0.04,
      'focus-opacity': 0.1,
      'selected-opacity': 0.08,
      'activated-opacity': 0.16,
      'pressed-opacity': 0.14,
      'disabled-opacity': 0.4,
      'dragged-opacity': 0.1,
      'border-color': '#97D5DE',
      'border-opacity': 0.12,
      'table-header-color': '#262925',
      'high-emphasis-opacity': 0.9,
      'medium-emphasis-opacity': 0.7,

      // 👉 Shadows
      'shadow-key-umbra-color': '#0B0D0A',
      'shadow-xs-opacity': '0.20',
      'shadow-sm-opacity': '0.22',
      'shadow-md-opacity': '0.24',
      'shadow-lg-opacity': '0.26',
      'shadow-xl-opacity': '0.28',
    },
  },
}

export default themes
