/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CardStatisticsHorizontal: typeof import('./src/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./src/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./src/@core/components/cards/CardStatisticsWithImages.vue')['default']
    ConfigurationMissing: typeof import('./src/components/kronos/ConfigurationMissing.vue')['default']
    ConnectionBadge: typeof import('./src/components/kronos/ConnectionBadge.vue')['default']
    DevicePending: typeof import('./src/components/kronos/DevicePending.vue')['default']
    EmptyState: typeof import('./src/components/kronos/EmptyState.vue')['default']
    ErrorHeader: typeof import('./src/components/ErrorHeader.vue')['default']
    GlobalSnackbar: typeof import('./src/components/kronos/GlobalSnackbar.vue')['default']
    KronosLogo: typeof import('./src/components/kronos/KronosLogo.vue')['default']
    MembershipPaymentDialog: typeof import('./src/components/kronos/MembershipPaymentDialog.vue')['default']
    MetricCard: typeof import('./src/components/kronos/MetricCard.vue')['default']
    ModulePlaceholder: typeof import('./src/components/kronos/ModulePlaceholder.vue')['default']
    MoreBtn: typeof import('./src/@core/components/MoreBtn.vue')['default']
    PageHeader: typeof import('./src/components/kronos/PageHeader.vue')['default']
    ReceiptDialog: typeof import('./src/components/kronos/ReceiptDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
    UpgradeToPro: typeof import('./src/components/UpgradeToPro.vue')['default']
    VueApexCharts: typeof import('vue3-apexcharts')['default']
  }
}
