/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountStatus: typeof import('./src/components/kronos/AccountStatus.vue')['default']
    AthleteIntakeFields: typeof import('./src/components/kronos/AthleteIntakeFields.vue')['default']
    BarcodeScanner: typeof import('./src/components/kronos/BarcodeScanner.vue')['default']
    CardStatisticsHorizontal: typeof import('./src/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./src/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./src/@core/components/cards/CardStatisticsWithImages.vue')['default']
    ConfigurationMissing: typeof import('./src/components/kronos/ConfigurationMissing.vue')['default']
    ConnectionBadge: typeof import('./src/components/kronos/ConnectionBadge.vue')['default']
    DevicePending: typeof import('./src/components/kronos/DevicePending.vue')['default']
    EmptyState: typeof import('./src/components/kronos/EmptyState.vue')['default']
    EnrollmentSheetDialog: typeof import('./src/components/kronos/EnrollmentSheetDialog.vue')['default']
    ErrorHeader: typeof import('./src/components/ErrorHeader.vue')['default']
    FirstAdminSetup: typeof import('./src/components/kronos/FirstAdminSetup.vue')['default']
    GlobalAlertCenter: typeof import('./src/components/kronos/GlobalAlertCenter.vue')['default']
    KioskCredentialCard: typeof import('./src/components/kronos/KioskCredentialCard.vue')['default']
    KioskCredentialDialog: typeof import('./src/components/kronos/KioskCredentialDialog.vue')['default']
    KronosLogo: typeof import('./src/components/kronos/KronosLogo.vue')['default']
    LoginScreen: typeof import('./src/components/kronos/LoginScreen.vue')['default']
    MembershipPaymentDialog: typeof import('./src/components/kronos/MembershipPaymentDialog.vue')['default']
    MetricCard: typeof import('./src/components/kronos/MetricCard.vue')['default']
    ModulePlaceholder: typeof import('./src/components/kronos/ModulePlaceholder.vue')['default']
    MoreBtn: typeof import('./src/@core/components/MoreBtn.vue')['default']
    PageHeader: typeof import('./src/components/kronos/PageHeader.vue')['default']
    PasswordChangeRequired: typeof import('./src/components/kronos/PasswordChangeRequired.vue')['default']
    ProductBarcodeLabelDialog: typeof import('./src/components/kronos/ProductBarcodeLabelDialog.vue')['default']
    ReceiptDialog: typeof import('./src/components/kronos/ReceiptDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
    UpgradeToPro: typeof import('./src/components/UpgradeToPro.vue')['default']
    VisitorPaymentDialog: typeof import('./src/components/kronos/VisitorPaymentDialog.vue')['default']
    VueApexCharts: typeof import('vue3-apexcharts')['default']
  }
}
